<a href="https://colab.research.google.com/github/Code0blivion/Ejercicios-M-todo-Simplex/blob/main/Metodo_Simplex_Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

#Luis David Bautista Pérez
#Cod. 20202020144
#Investigación de Operaciones I
#Problemas propuestos

#Los enunciados de los problemas fueron proporcionados por el profesor en el archivo adjunto que envió, por lo que se pasará directamente a la solución

print("PROBLEMA PROPUESTO #1")

print("Maximizar P = 200x + 100y")
print("Sujeto a:")
print("5x + 3y =< 105")
print("2x + 4y =< 70")
print("x >= 0")
print("y >= 0")

print("Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales")
matriz = np.array([[5,3,1,0,105],[2,4,0,1,70],[200,100,0,0,0]])

print(matriz)

print()

print("Despues de hacer el analisis el pivote es el 4 en la fila #2")
print("Convertimos el pivote a 1, por lo que multiplicamos toda la fila #2 por 1/4")

matriz = np.array([[5,3,1,0,105],[1/2,1,0,1/4,35/2],[200,100,0,0,0]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones: -3f2 + f1, -100f2 + f3")

matriz = np.array([[7/2,0,1,-3/4,105/2],[1/2,1,0,1/4,35/2],[150,0,0,-25,-1750]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Ahora tomamos el 7/2 de la primera fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 2/7")

matriz = np.array([[1,0,2/7,-3/14,15],[1/2,1,0,1/4,35/2],[150,0,0,-25,-1750]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones -1/2f1 + f2, -150f1 + f3")

matriz = np.array([[1,0,2/7,-3/14,15],[0,1,-1/7,5/14,10],[0,0,-300/7,50/7,-4000]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("El nuevo pivote es el 5/14 de la fila #2, para transformarlo a 1 se multiplica dicha fila por 14/5")

matriz = np.array([[1,0,2/7,-3/14,15],[0,14/5,-2/5,1,28],[0,0,-300/7,50/7,-4000]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Se realizan las siguientes operaciones: 3/14f2 + f1, -50/7f2 + f3 ")

matriz = np.array([[1,3/5,1/5,0,21],[0,14/5,-2/5,1,28],[0,-20,-40,0,-4200]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Como se puede apreciar en la ultima matriz, el valor de P se maximiza cuando se fabrican 21 unidades del producto \
x y ninguna unidad del producto y. Se obtiene una utilidad maxima de 4200$")

PROBLEMA PROPUESTO #1
Maximizar P = 200x + 100y
Sujeto a:
5x + 3y =< 105
2x + 4y =< 70
x >= 0
y >= 0
Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales
[[  5   3   1   0 105]
 [  2   4   0   1  70]
 [200 100   0   0   0]]

Despues de hacer el analisis el pivote es el 4 en la fila #2
Convertimos el pivote a 1, por lo que multiplicamos toda la fila #2 por 1/4
[[  5.     3.     1.     0.   105.  ]
 [  0.5    1.     0.     0.25  17.5 ]
 [200.   100.     0.     0.     0.  ]]

Realizamos las siguientes operaciones: -3f2 + f1, -100f2 + f3
[[    3.5      0.       1.      -0.75    52.5 ]
 [    0.5      1.       0.       0.25    17.5 ]
 [  150.       0.       0.     -25.   -1750.  ]]

Ahora tomamos el 7/2 de la primera fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 2/7
[[    1.        0.        0.286    -0.214    15.   ]
 [    0.5       1.        0.        0.25     17.5  ]
 [  150.        0.        0.      -25.    -1750.   ]]

Realizam

In [5]:
import numpy as np

#Luis David Bautista Pérez
#Cod. 20202020144
#Investigación de Operaciones I
#Problemas de maximización y minimización

#Los enunciados de los problemas están en el PDF de las soluciones a mano

print("PROBLEMA DE MAXIMIZACION #1")

print("Maximizar P = 7x + 8y")
print("Sujeto a:")
print("2x + y =< 19")
print("x + y =< 14")
print("x + 2y =< 20")

print("Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales")
matriz = np.array([[2,1,1,0,0,19],[1,1,0,1,0,14],[1,2,0,0,1,20],[7,8,0,0,0,0]])

print(matriz)

print()

print("Despues de hacer el analisis el pivote es el 2 en la fila #3")
print("Convertimos el pivote a 1, por lo que multiplicamos toda la fila #3 por 1/2")

matriz = np.array([[2,1,1,0,0,19],[1,1,0,1,0,14],[1/2,1,0,0,1/2,10],[7,8,0,0,0,0]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones: -f3 + f1, -f3 + f2, -8f3 + f4")

matriz = np.array([[3/2,0,1,0,-1/2,9],[1/2,0,0,1,-1/2,4],[1/2,1,0,0,1/2,10],[3,0,0,0,-4,-80]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Ahora tomamos el 3/2 de la primera fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 2/3")

matriz = np.array([[1,0,2/3,0,-1/3,6],[1/2,0,0,1,-1/2,4],[1/2,1,0,0,1/2,10],[3,0,0,0,-4,-80]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones -1/2f1 + f2, -1/2f1 + f3, -3f1 + f4")

matriz = np.array([[1,0,2/3,0,-1/3,6],[0,0,-1/3,1,-1/3,1],[0,1,-1/3,0,2/3,7],[0,0,-2,0,-3,-98]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()


print("Como se puede apreciar en la ultima matriz, el valor de P se maximiza cuando se fabrican 6 asientos A1 \
 y 7 asientos A2. Se obtiene un beneficio maximo de 98000 pesetas")

print()

print("PROBLEMA DE MAXIMIZACION #2")

print("Maximizar P = 8x + 6y")
print("Sujeto a:")
print("4x + 2y =< 60")
print("2x + 4y =< 48")
print("6x + 2y =< 76")

print("Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales")
matriz = np.array([[4,2,1,0,0,60],[2,4,0,1,0,48],[6,2,0,0,1,76],[8,6,0,0,0,0]])

print(matriz)

print()

print("Despues de hacer el analisis el pivote es el 6 en la fila #3")
print("Convertimos el pivote a 1, por lo que multiplicamos toda la fila #3 por 1/6")

matriz = np.array([[4,2,1,0,0,60],[2,4,0,1,0,48],[1,1/3,0,0,1/6,38/3],[8,6,0,0,0,0]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones: -4f3 + f1, -2f3 + f2, -8f3 + f4")

matriz = np.array([[0,2/3,1,0,-2/3,28/3],[0,10/3,0,1,-1/3,68/3],[1,1/3,0,0,1/6,38/3],[0,10/3,0,0,-4/3,-304/3]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Ahora tomamos el 10/3 de la segunda fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 3/10")

matriz = np.array([[0,2/3,1,0,-2/3,28/3],[0,1,0,3/10,-1/10,34/5],[1,1/3,0,0,1/6,38/3],[0,10/3,0,0,-4/3,-304/3]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones -2/3f2 + f1, -1/3f2 + f3, -10/3f2 + f4")

matriz = np.array([[0,0,1,-1/5,-3/5,24/5],[0,1,0,3/10,-1/10,34/5],[1,0,0,-1/10,1/5,52/5],[0,0,0,-1,-1,-124]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()


print("Como se puede apreciar en la ultima matriz, el valor de P se maximiza cuando se fabrican 10.4 unidades de la lamina 1 \
 y 6.8 unidades de la lamina 2. Se obtiene un beneficio maximo de 124000 pesetas")

print()

print("PROBLEMA DE MINIMIZACION #1")

print("MINIMIZAR P = 400x + 1000y")
print("Sujeto a:")
print("x =< 80")
print("y =< 80")
print("6x + 10y =< 1000")

print("Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales")
matriz = np.array([[6,10,1,0,0,1000],[1,0,0,1,0,80],[0,1,0,0,1,80],[400,1000,0,0,0,0]])

print(matriz)

print()

print("Despues de hacer el analisis el pivote es el 1 en la fila #3")
print("Se realizan las siguientes operaciones: -10f3 + f1, -1000f3 + f4")

matriz = np.array([[6,0,1,0,-10,200],[1,0,0,1,0,80],[0,1,0,0,1,80],[400,0,0,0,-1000,-80000]])

with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("El nuevo pivote es el 6 en la fila #1, por lo que multiplicamos toda la fila por 1/6")

matriz = np.array([[1,0,1/6,0,-5/3,100/3],[1,0,0,1,0,80],[0,1,0,0,1,80],[400,0,0,0,-1000,-80000]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()


print("Realizamos las siguientes operaciones -f1 + f2, -400f1 + f4")

matriz = np.array([[1,0,1/6,0,-5/3,100/3],[0,0,-1/6,1,5/3,140/3],[0,1,0,0,1,80],[0,0,-200/3,0,-1000/3,-93333.3333]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()


print("Como se puede apreciar en la ultima matriz, el valor de P se minimiza cuando se le asignan 33.3 horas al primer contador y 80 horas al segundo contador.")
print("Dando como resultado un coste minimo de 93333.3333 pesetas")
print()


print("PROBLEMA DE MINIMIZACION #2")

print("MINIMIZAR P = 3x + 2y")
print("Sujeto a:")
print("2x + 2y =< 12")
print("5x + y =< 12")
print("x + 4y =< 12")

print("Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales")
matriz = np.array([[5,1,1,0,0,12],[2,2,0,1,0,12],[1,4,0,0,1,12],[3,2,0,0,0,0]])

print(matriz)

print()

print("Despues de hacer el analisis el pivote es el 5 en la fila #1")
print("Convertimos el pivote a 1, por lo que multiplicamos toda la fila #1 por 1/5")

matriz = np.array([[1,1/5,1/5,0,0,12/5],[2,2,0,1,0,12],[1,4,0,0,1,12],[3,2,0,0,0,0]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones: -2f1 + f2, -f1 + f3, -3f1 + f4")

matriz = np.array([[1,1/5,1/5,0,0,12/5],[0,8/5,-2/5,1,0,36/5],[0,19/5,-1/5,0,1,48/5],[0,7/5,-3/5,0,0,-36/5]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Ahora tomamos el 19/5 de la tercera fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 5/19")

matriz = np.array([[1,1/5,1/5,0,0,12/5],[0,8/5,-2/5,1,0,36/5],[0,1,-1/19,0,5/19,48/19],[0,7/5,-3/5,0,0,-36/5]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()

print("Realizamos las siguientes operaciones -1/5f3 +f1, -8/5f3 + f2, -7/5f3 +f4")

matriz = np.array([[1,0,4/19,0,-1/19,36/19],[0,0,-6/19,1,-8/19,60/19],[0,1,-1/19,0,5/19,48/19],[0,0,-10/19,0,-7/19,-10.74]])
with np.printoptions(precision=3, suppress=True):
    print(matriz)

print()


print("Como se puede apreciar en la ultima matriz, el valor de P se minimiza cuando el animal rapaz se come casi 1.89 animales de la especie 1 y 2.52 animales de la especie 2.")
print("Con el objetivo de gastar un minimo de 10.74 unidades de energia")


PROBLEMA DE MAXIMIZACION #1
Maximizar P = 7x + 8y
Sujeto a:
2x + y =< 19
x + y =< 14
x + 2y =< 20
Se arma una matriz aumentada con los coeficientes del sistema y las variables artificiales
[[ 2  1  1  0  0 19]
 [ 1  1  0  1  0 14]
 [ 1  2  0  0  1 20]
 [ 7  8  0  0  0  0]]

Despues de hacer el analisis el pivote es el 2 en la fila #3
Convertimos el pivote a 1, por lo que multiplicamos toda la fila #3 por 1/2
[[ 2.   1.   1.   0.   0.  19. ]
 [ 1.   1.   0.   1.   0.  14. ]
 [ 0.5  1.   0.   0.   0.5 10. ]
 [ 7.   8.   0.   0.   0.   0. ]]

Realizamos las siguientes operaciones: -f3 + f1, -f3 + f2, -8f3 + f4
[[  1.5   0.    1.    0.   -0.5   9. ]
 [  0.5   0.    0.    1.   -0.5   4. ]
 [  0.5   1.    0.    0.    0.5  10. ]
 [  3.    0.    0.    0.   -4.  -80. ]]

Ahora tomamos el 3/2 de la primera fila como pivote. Lo convertimos a 1 multiplicando toda la fila por 2/3
[[  1.      0.      0.667   0.     -0.333   6.   ]
 [  0.5     0.      0.      1.     -0.5     4.   ]
 [  0.5     1.    